### ISSUE TITLE
Unable to start APE service

### ISSUE THREAD

**Issue by ontheway-arch** [Leon1207/Video-RAG-master#3]
Thank you for your excellent work. I encountered the following problems when running demo/ape_service.py

Traceback (most recent call last):
  File "demo/ape_service.py", line 36, in <module>
    main()
  File "demo/ape_service.py", line 8, in main
    demo = VisualizationDemo(cfg, args=None)
  File "/data1/xingyc/project/LLaVA-NeXT-main/APE/demo/predictor_lazy.py", line 177, in __init__
    self.predictor = DefaultPredictor(cfg)
  File "/data1/xingyc/project/LLaVA-NeXT-main/APE/ape/engine/defaults.py", line 194, in __init__
    checkpointer.load(cfg.train.init_checkpoint)
  File "/data1/xingyc/anaconda3/envs/ape/lib/python3.8/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 62, in load
    ret = super().load(path, *args, **kwargs)
  File "/data1/xingyc/anaconda3/envs/ape/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 153, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint /checkpoints/model_final.pth not found!

**Comment by Leon1207** [comment]
Please refer to APE and load the right checkpoint.

**Comment by ontheway-arch** [comment]
Thanks for your reply, I solved this problem by downloading the weights manually.
But I encountered a new problem, the following problems occurred in lines 219 and 225 of vidrag_pipeline：

Traceback (most recent call last):
  File "/data1/xingyc/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/feature_extraction_utils.py", line 182, in convert_to_tensors
    tensor = as_tensor(value)
  File "/data1/xingyc/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/feature_extraction_utils.py", line 141, in as_tensor
    return torch.tensor(value)
RuntimeError: Could not infer dtype of numpy.float32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data1/xingyc/anaconda3/envs/llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data1/xingyc/anaconda3/envs/llava/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xingyc/.vscode-server/extensions/ms-python.debugpy-2024.12.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/home/xingyc/.vscode-server/extensions/ms-python.debugpy-2024.12.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 501, in main
    run()
  File "/home/xingyc/.vscode-server/extensions/ms-python.debugpy-2024.12.0/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/xingyc/.vscode-server/extensions/ms-python.debugpy-2024.12.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
  File "/home/xingyc/.vscode-server/extensions/ms-python.debugpy-2024.12.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "/home/xingyc/.vscode-server/extensions/ms-python.debugpy-2024.12.0/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "/data1/xingyc/project/LLaVA-NeXT-main/vidrag_pipeline.py", line 225, in <module>
    processed = clip_processor(images=frame, return_tensors="pt")["pixel_values"].to(clip_model.device, dtype=torch.float16)
  File "/data1/xingyc/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/clip/processing_clip.py", line 104, in __call__
    image_features = self.image_processor(images, return_tensors=return_tensors, **kwargs)
  File "/data1/xingyc/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/image_processing_utils.py", line 551, in __call__
    return self.preprocess(images, **kwargs)
  File "/data1/xingyc/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/models/clip/image_processing_clip.py", line 346, in preprocess
    return BatchFeature(data=data, tensor_type=return_tensors)
  File "/data1/xingyc/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/feature_extraction_utils.py", line 78, in __init__
    self.convert_to_tensors(tensor_type=tensor_type)
  File "/data1/xingyc/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/feature_extraction_utils.py", line 188, in convert_to_tensors
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate padding with 'padding=True' to have batched tensors with the same length.

**Comment by Leon1207** [comment]
This may be the incorrect transformer version. Try updating it,

**Comment by ontheway-arch** [comment]
Can you tell me the versions of numpy and transformers?

**Comment by ontheway-arch** [comment]
Thanks. I found that lowering the spacy version to 3.7.0 solved it.

**Comment by paprika0741** [comment]
> Thank you for your excellent work. I encountered the following problems when running demo/ape_service.py
> 
> Traceback (most recent call last): File "demo/ape_service.py", line 36, in main() File "demo/ape_service.py", line 8, in main demo = VisualizationDemo(cfg, args=None) File "/data1/xingyc/project/LLaVA-NeXT-main/APE/demo/predictor_lazy.py", line 177, in **init** self.predictor = DefaultPredictor(cfg) File "/data1/xingyc/project/LLaVA-NeXT-main/APE/ape/engine/defaults.py", line 194, in **init** checkpointer.load(cfg.train.init_checkpoint) File "/data1/xingyc/anaconda3/envs/ape/lib/python3.8/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 62, in load ret = super().load(path, *args, **kwargs) File "/data1/xingyc/anaconda3/envs/ape/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 153, in load assert os.path.isfile(path), "Checkpoint {} not found!".format(path) AssertionError: Checkpoint /checkpoints/model_final.pth not found!

![Image](https://github.com/user-attachments/assets/6c37da7e-ec0c-4413-b200-051e3e67c087)
Hi, I’m encountering the same issue. Do I need to download all of them, or can I just choose one at random?

**Comment by Leon1207** [comment]
> > Thank you for your excellent work. I encountered the following problems when running demo/ape_service.py
> > Traceback (most recent call last): File "demo/ape_service.py", line 36, in main() File "demo/ape_service.py", line 8, in main demo = VisualizationDemo(cfg, args=None) File "/data1/xingyc/project/LLaVA-NeXT-main/APE/demo/predictor_lazy.py", line 177, in **init** self.predictor = DefaultPredictor(cfg) File "/data1/xingyc/project/LLaVA-NeXT-main/APE/ape/engine/defaults.py", line 194, in **init** checkpointer.load(cfg.train.init_checkpoint) File "/data1/xingyc/anaconda3/envs/ape/lib/python3.8/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 62, in load ret = super().load(path, *args, **kwargs) File "/data1/xingyc/anaconda3/envs/ape/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 153, in load assert os.path.isfile(path), "Checkpoint {} not found!".format(path) AssertionError: Checkpoint /checkpoints/model_final.pth not found!
> 
> ![Image](https://github.com/user-attachments/assets/6c37da7e-ec0c-4413-b200-051e3e67c087) Hi, I’m encountering the same issue. Do I need to download all of them, or can I just choose one at random?

You can choose one of them, for example, the first one.

**Comment by paprika0741** [comment]
> > > Thank you for your excellent work. I encountered the following problems when running demo/ape_service.py
> > > Traceback (most recent call last): File "demo/ape_service.py", line 36, in main() File "demo/ape_service.py", line 8, in main demo = VisualizationDemo(cfg, args=None) File "/data1/xingyc/project/LLaVA-NeXT-main/APE/demo/predictor_lazy.py", line 177, in **init** self.predictor = DefaultPredictor(cfg) File "/data1/xingyc/project/LLaVA-NeXT-main/APE/ape/engine/defaults.py", line 194, in **init** checkpointer.load(cfg.train.init_checkpoint) File "/data1/xingyc/anaconda3/envs/ape/lib/python3.8/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 62, in load ret = super().load(path, *args, **kwargs) File "/data1/xingyc/anaconda3/envs/ape/lib/python3.8/site-packages/fvcore/common/checkpoint.py", line 153, in load assert os.path.isfile(path), "Checkpoint {} not found!".format(path) AssertionError: Checkpoint /checkpoints/model_final.pth not found!
> > 
> > 
> > ![Image](https://github.com/user-attachments/assets/6c37da7e-ec0c-4413-b200-051e3e67c087) Hi, I’m encountering the same issue. Do I need to download all of them, or can I just choose one at random?
> 
> You can choose one of them, for example, the first one.

Thank you!
